---
- name: setup tomcat
  hosts: all 
  become: true

  tasks: 
  - name: install java in RedHat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install java in Debian
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"
    
  - name: download tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.70/bin/apache-tomcat-8.5.70.tar.gz
      dest: /opt 

  - name: extract tomcat 
    unarchive: 
      src: /opt/apache-tomcat-8.5.70.tar.gz
      dest: /opt
      remote_src: True

  - name: Execute permissions 
    file:
      path: /opt/apache-tomcat-8.5.70/bin/startup.sh
      mode: 0777 
      
  - name: Start tomcat service     
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.70/bin







